wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.4
    code_path: code/JSS/dqn.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
activation:
  desc: null
  value: tanh
actors_per_cpu:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 64
env_name:
  desc: null
  value: job-shop-v0
epsilon:
  desc: null
  value: 0.9
epsilon_decay:
  desc: null
  value: 0.995
gamma:
  desc: null
  value: 0.999
instances:
  desc: null
  value:
  - env/instances/ta51
  - env/instances/ta52
  - env/instances/ta53
  - env/instances/ta54
  - env/instances/ta55
layer_nb:
  desc: null
  value: 3
layer_size:
  desc: null
  value: 4096
learning_rate:
  desc: null
  value: 0.001
max_steps_per_episode:
  desc: null
  value: 1000
minimal_epsilon:
  desc: null
  value: 0.1
nb_steps:
  desc: null
  value: 16
replay_buffer_size:
  desc: null
  value: 500000
running_sec_time:
  desc: null
  value: 3600
seed:
  desc: null
  value: 0
tau:
  desc: null
  value: 0.001
update_network_step:
  desc: null
  value: 5
